### ISSUE TITLE
Final castone Kanban board

### ISSUE THREAD

**Issue by tmampa** [tmampa/car-rentals-rails-backend#15]
# Project link: https://github.com/tmampa/car-rentals-rails-backend

### Only 1 member (Me)
![Screenshot from 2022-03-22 12-44-03](https://user-images.githubusercontent.com/67906597/159465652-d21c5d96-66f8-4380-8f59-2379d772c565.png)

**Comment by MuriloRoque** [comment]
Hi @tmampa,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the issue thread if something is not 100% clear.
